# Generated by Django 3.2 on 2021-04-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='media/imgs/'),
        ),
    ]
