# Generated by Django 3.2 on 2021-04-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0005_auto_20210417_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musica',
            name='acertou',
        ),
        migrations.AddField(
            model_name='userresps',
            name='acertou',
            field=models.BooleanField(default=False),
        ),
    ]
