# Generated by Django 3.2 on 2021-04-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0006_auto_20210417_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='fase',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musica',
            name='tipo',
            field=models.CharField(default='anime', max_length=255),
            preserve_default=False,
        ),
    ]
