# Generated by Django 3.2 on 2021-04-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0008_userresps_pontuacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresps',
            name='pontuacao',
        ),
    ]
