# Generated by Django 3.2 on 2021-05-08 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0012_auto_20210507_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdicas',
            name='fase_lista',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='musicas.musica'),
            preserve_default=False,
        ),
    ]
