# Generated by Django 3.2 on 2021-05-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0013_userdicas_fase_lista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdicas',
            name='fase_lista',
        ),
        migrations.AddField(
            model_name='userdicas',
            name='fase',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
