# Generated by Django 3.2 on 2021-05-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0015_userdicas_pontuacaotema'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='dica',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
