# Generated by Django 3.2 on 2021-05-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0016_musica_dica'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='info',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
