# Generated by Django 3.2 on 2021-05-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0017_musica_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresps',
            name='usou_dica',
            field=models.BooleanField(default=False),
        ),
    ]
